### ISSUE TITLE
Quick installer does not give option to select or create installation folder

### ISSUE THREAD

**Issue by bajwa-adobe** [adobe/UST-Install-Scripts#2]
Currently on windows OS, the installer need to give option to select or create installation folder.

Meanwhile, please update the README 
> Please run the command-line installer from location you like to have UST installed

**Comment by vossen-adobe** [comment]
This functionality was removed intentionally originally since it mandated that the platform be GUI based.  However, since essentially all windows installs are GUI based anyway, I have no objection to reintroducing this feature in a try catch to suit both cases, since we may see more headless windows VM's in the future.

**Comment by bajwa-adobe** [comment]
Ok, 
I think it would be helpful to update README instructions to run command-line from the location you like to have UST installed. It was not obvious to me when I ran it first time.

**Comment by vossen-adobe** [comment]
Feature added! In the case of no gui (rare), the script will default to install in the current directory.  This feature tested with paths ending in \ (C:\) and paths with spaces, and all work well.  Forgot to link the commit, but you can find it here:

https://github.com/adobe/UST-Install-Scripts/commit/0dc9a10e4dcbaf8dddc0206f9d1794588cf5116f
