### ISSUE TITLE
An error occurred in the UST built with AdobeUSTSetup.msi.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe/UST-Install-Scripts#6]
AdobeUSTSetup.msi version is 2.5.

error is below.
--------------------
C:\Program Files\Adobe\Adobe User Sync Tool>python user-sync.pex -v
  File "user-sync.pex", line 1
SyntaxError: Non-UTF-8 code starting with '\x8b' in file user-sync.pex on line 1
, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
--------------------

Is the character code correctly setting?

**Comment by vossen-adobe** [comment]
Hello - can you please double check that you have used the [latest](https://github.com/adobe/UST-Install-Scripts/releases/latest) MSI? This was a bug in a previous version, but I can't reproduce it now on any version of windows.  Additionally, could you tell me which version of windows / python you got this on or anything else about your environment? Also, could you provide me a copy of the user-sync pex?

Originally the issue was a typo which cause the pex file to be extracted incorrectly.  The sync tool is pulled straight from its release page on build, so there should not be any encoding changes along the way.

**Comment by Tomomi99145** [comment]
Thank you for your response.
I checked it again and noticed that it was not latest MSI.
I solved it. Thank you very much!

**Comment by vossen-adobe** [comment]
Closed
